### ISSUE TITLE
Entities and cache

### ISSUE THREAD

**Issue by jorenmartijn** [analogueorm/analogue#17]
Hi, I'm trying to use this in a project and all worked fine until I dropped the table I was working with from the database in order to change some columns. Now I get this error:
`Fatal error: Uncaught exception 'Analogue\ORM\Exceptions\MappingException' with message 'Entity primary key contradicts with cached Entity. You probably modified it by mistake' in /Server/redbooth/vendor/analogue/orm/src/System/StateChecker.php:81 Stack trace: #0 
/Server/redbooth/vendor/analogue/orm/src/Commands/Store.php(81): Analogue\ORM\System\StateChecker->exists() #1 /Server/redbooth/vendor/analogue/orm/src/System/Mapper.php(141): Analogue\ORM\Commands\Store->execute() #2 /Server/redbooth/vendor/analogue/orm/src/System/Mapper.php(104): Analogue\ORM\System\Mapper->storeEntity(Object(Project)) #3 /Server/redbooth/index.php(16): Analogue\ORM\System\Mapper->store(Object(Project)) #4 {main} thrown in /Server/redbooth/vendor/analogue/orm/src/System/StateChecker.php on line 81`
It mentions an Entity cache, but I can't seem to flush that because I can't find where it's supposed to store the Entity cache.

This is my model:
```php
<?php
use Analogue\ORM\Entity;

class Project extends Entity
{
    public function __construct($id, $name, $created_at, $updated_at)
    {
    	$this->id = $id;
        $this->name = $name;
        $this->created_at = $created_at;
        $this->updated_at = $updated_at;
    }
}
?>
```
projects.id is the primary key but not auto-incrementing because it shouldn't. 

How do I drop or flush the entity cache?

**Comment by jorenmartijn** [comment]
Sorry, false alarm, I solved it by adding an entitymap to my model.
